
using Pantry;
using Pantry.Data;
using Pantry.Models;

namespace Pantry.Migrations
{
  public class SeedPantryItems
  {
    public static async Task SeedData(PantryDBContext context)
    {
      if (context.Ingredients.Any()) return;

            var item = new List<Ingredient>

            {
                new Ingredient
                {
                    //Id =  1,
                    ItemName = "Apple",
                    Protein = 1,
                    Type = FoodType.Fruit,
                    Carbohydrates = 25,
                    Sugar = 19,
                    Calories = 95,
                    Weight = 182,
                    Fat = 0,
                    ImageUrl = "https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBwbGV8ZW58MHx8MHx8fDA%3D",
                },
                new Ingredient{

                  //Id =  2,
                  ItemName= "Banana",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 27,
                  Sugar = 14,
                  Calories= 105,
                  Weight= 118,
                  Fat= 0,
                ImageUrl= "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmFuYW5hfGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  3,
                  ItemName= "Orange",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 21,
                  Sugar = 12,
                  Calories= 62,
                  Weight= 131,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1557800636-894a64c1696f?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                },
                  new Ingredient{
                  //Id =  4,
                  ItemName= "Grapes",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 16,
                  Sugar = 23,
                  Calories= 62,
                  Weight= 151,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1625499940894-8796928bf9c4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Z3JhcGVzfGVufDB8fDB8fHww"
                },
                  new Ingredient{
              //Id =  5,
                  ItemName= "Pineapple",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 13,
                  Sugar = 16,
                  Calories= 50,
                  Weight= 905,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGluZWFwcGxlfGVufDB8fDB8fHww"
                },
                  new Ingredient{
              //Id =  6,
                  ItemName= "Strawberry",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 7,
                  Sugar = 7,
                  Calories= 33,
                  Weight= 152,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3RyYXdiZXJyeXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  7,
                  ItemName= "Watermelon",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 8,
                  Sugar = 9,
                  Calories= 30,
                  Weight= 286,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2F0ZXJtZWxvbnxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  8,
                  ItemName= "Kiwi",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 15,
                  Sugar = 13,
                  Calories= 61,
                  Weight= 183,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a2l3aXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  9,
                  ItemName= "Mango",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 25,
                  Sugar = 23,
                  Calories= 99,
                  Weight= 336,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFuZ298ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
              //Id =  10,
                  ItemName= "Pear",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 15,
                  Calories= 58,
                  Weight= 178,
                  Fat= 0,
                  ImageUrl = "https://plus.unsplash.com/premium_photo-1669905375079-5d7e074fc123?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8UGVhcnxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  11,
                  ItemName= "Peach",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 15,
                  Sugar = 17,
                  Calories= 39,
                  Weight= 150,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1602813812581-0713dae489da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGVhY2h8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
              //Id =  12,
                  ItemName= "Plum",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 11,
                  Sugar = 8,
                  Calories= 46,
                  Weight= 66,
                  Fat= 0,
                  ImageUrl= "https://plus.unsplash.com/premium_photo-1675234386336-ed98399765d2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8UGx1bXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  13,
                  ItemName= "Cherry",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 9,
                  Sugar = 18,
                  Calories= 50,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1528821154947-1aa3d1b74941?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2hlcnJ5fGVufDB8fDB8fHww"
                },
                  new Ingredient{
              //Id =  14,
                  ItemName= "Grapefruit",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 11,
                  Sugar = 8,
                  Calories= 42,
                  Weight= 230,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1622912789333-ba8bf8242e27?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JhcGVmcnVpdHxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  15,
                  ItemName= "Lemon",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 9,
                  Sugar = 1,
                  Calories= 29,
                  Weight= 58,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/flagged/photo-1587302164675-820fe61bbd55?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TGVtb258ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
              //Id =  16,
                  ItemName= "Lime",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 11,
                  Sugar = 1,
                  Calories= 30,
                  Weight= 67,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1620101680155-b251043b700b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGltZXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  17,
                  ItemName= "Cantaloupe",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 8,
                  Sugar = 13,
                  Calories= 34,
                  Weight= 552,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1638865553538-2434be4c62bd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Q2FudGFsb3VwZXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
              //Id =  18,
                  ItemName= "Apricot",
                  Protein= 1,
                  Type = FoodType.Fruit,
                  Carbohydrates= 15,
                  Sugar = 9,
                  Calories= 48,
                  Weight= 35,
                  Fat= 0,
                  ImageUrl= "https://images.unsplash.com/photo-1627931754115-478ed65b4fef?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8QXByaWNvdHxlbnwwfHwwfHx8MA%3D%3D"
                  },
                  new Ingredient  {
                  //Id =  19,
                  ItemName= "Carrot",
                  Protein= 9,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 96,
                  Sugar = 6,
                  Calories= 41,
                  Weight= 100,
                  Fat= 2,
                  ImageUrl = "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2Fycm90fGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  20,
                  ItemName= "Broccoli",
                  Protein= 28,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 66,
                  Sugar = 2,
                  Calories= 34,
                  Weight= 100,
                  Fat= 4,
                  ImageUrl ="https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QnJvY2NvbGl8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  21,
                  ItemName= "Tomato",
                  Protein= 9,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 39,
                  Sugar = 4,
                  Calories= 18,
                  Weight= 100,
                  Fat= 2,
                  ImageUrl="https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG9tYXRvfGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  22,
                  ItemName= "Spinach",
                  Protein= 29,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 36,
                  Sugar = 1,
                  Calories= 23,
                  Weight= 100,
                  Fat= 4,
                  ImageUrl="https://images.unsplash.com/photo-1580910365203-91ea9115a319?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3BpbmFjaHxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
                  //Id =  23,
                  ItemName= "Bell Pepper",
                  Protein= 13,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 60,
                  Sugar = 6,
                  Calories= 31,
                  Weight= 100,
                  Fat= 3,
                  ImageUrl="https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?q=80&w=2020&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                },
                  new Ingredient{
                  //Id =  24,
                  ItemName= "Potato",
                  Protein= 20,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 170,
                  Sugar = 2,
                  Calories= 77,
                  Weight= 100,
                  Fat= 1,
                  ImageUrl="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG90YXRvfGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  25,
                  ItemName= "Cucumber",
                  Protein= 7,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 36,
                  Sugar = 2,
                  Calories= 16,
                  Weight= 100,
                  Fat= 2,
                  ImageUrl="https://images.unsplash.com/photo-1589621316382-008455b857cd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y3VjdW1iZXJ8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  26,
                  ItemName= "Onion",
                  Protein= 11,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 93,
                  Sugar = 5,
                  Calories= 40,
                  Weight= 100,
                  Fat= 1,
                  ImageUrl="https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8T25pb258ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  27,
                  ItemName= "Lettuce",
                  Protein= 14,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 29,
                  Sugar = 1,
                  Calories= 15,
                  Weight= 100,
                  Fat= 2,
                  ImageUrl="https://plus.unsplash.com/premium_photo-1678198891411-46073f3c2cdb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8TGV0dHVjZXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
                  //Id =  28,
                  ItemName= "Cauliflower",
                  Protein= 19,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 49,
                  Sugar = 2,
                  Calories= 25,
                  Weight= 100,
                  Fat= 3,
                  ImageUrl="https://images.unsplash.com/photo-1613743990305-736d763f3d70?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2F1bGlmbG93ZXJ8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  29,
                  ItemName= "Zucchini",
                  Protein= 1,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 3,
                  Sugar = 2,
                  Calories= 17,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1580294672675-91afc00ee7b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8enVjY2hpbml8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  30,
                  ItemName= "Kale",
                  Protein= 4,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 10,
                  Sugar = 1,
                  Calories= 50,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a2FsZXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
                  //Id =  31,
                  ItemName= "Artichoke",
                  Protein= 3,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 14,
                  Sugar = 1,
                  Calories= 47,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1551465222-21f38590e0ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8QXJ0aWNob2tlfGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  32,
                  ItemName= "Beetroot",
                  Protein= 1,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 10,
                  Sugar = 13,
                  Calories= 43,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1503623758111-863eb2abd7a9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVldHJvb3R8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  33,
                  ItemName= "Radish",
                  Protein= 1,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 4,
                  Sugar = 4,
                  Calories= 16,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1656232507287-0a168a01957a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8UmFkZGlzaHxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
                  //Id =  34,
                  ItemName= "Asparagus",
                  Protein= 2,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 3,
                  Sugar = 2,
                  Calories= 20,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1629875235163-2e52306e4018?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXNwYXJhZ3VzfGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  35,
                  ItemName= "Brussels Sprouts",
                  Protein= 4,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 9,
                  Sugar = 4,
                  Calories= 43,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1614087434853-25e6e8357217?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YnJ1c3NlbCUyMHNwcm91dHN8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                  //Id =  36,
                  ItemName= "Cabbage",
                  Protein= 1,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 6,
                  Sugar = 2,
                  Calories= 25,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FiYmFnZXxlbnwwfHwwfHx8MA%3D%3D"
                },
                  new Ingredient{
                  //Id =  37,
                  ItemName= "Celery",
                  Protein= 0,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 3,
                  Sugar = 2,
                  Calories= 16,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1580391564590-aeca65c5e2d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2VsZXJ5fGVufDB8fDB8fHww"
                },
                  new Ingredient{
                  //Id =  38,
                  ItemName= "Eggplant",
                  Protein= 1,
                  Type = FoodType.Vegetables,
                  Carbohydrates= 6,
                  Sugar = 5,
                  Calories= 25,
                  Weight= 100,
                  Fat= 0,
                  ImageUrl="https://images.unsplash.com/photo-1615484477201-9f4953340fab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWdncGxhbnR8ZW58MHx8MHx8fDA%3D"
                },
                  new Ingredient{
                //Id =  39,
                ItemName= "Chicken Breast",
                Protein= 31,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 165,
                Weight= 100,
                Fat= 3,
                ImageUrl="https://images.unsplash.com/photo-1633096013004-e2cb4023b560?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2hpY2tlbiUyMGJyZWFzdHxlbnwwfHwwfHx8MA%3D%3D"
              },
                new Ingredient{
                //Id =  40,
                ItemName= "Ground Beef (90% Lean)",
                Protein= 27,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 250,
                Weight= 100,
                Fat= 10,
                ImageUrl="https://plus.unsplash.com/premium_photo-1668616817140-bc9385635319?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fGdyb3VuZCUyMGJlZWZ8ZW58MHx8MHx8fDA%3D"
              },
                new Ingredient{
                //Id =  41,
                ItemName= "Salmon Fillet",
                Protein= 20,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 206,
                Weight= 100,
                Fat= 13,
                ImageUrl="https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U2FsbW9uJTIwRmlsbGV0fGVufDB8fDB8fHww"
              },
                new Ingredient{
                //Id =  42,
                ItemName= "Pork Chop",
                Protein= 24,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 193,
                Weight= 100,
                Fat= 11,
                ImageUrl="https://images.unsplash.com/photo-1597398230884-35763d59ed15?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UG9yayUyMENob3B8ZW58MHx8MHx8fDA%3D"
              },
                new Ingredient{
                //Id =  43,
                ItemName= "Turkey Breast",
                Protein= 29,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 135,
                Weight= 100,
                Fat= 1,
                ImageUrl="https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHVya2V5JTIwYnJlYXN0fGVufDB8fDB8fHww"
              },
                new Ingredient{
                //Id =  44,
                ItemName= "Lamb Chop",
                Protein= 25,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 258,
                Weight= 100,
                Fat= 15,
                ImageUrl="https://images.unsplash.com/photo-1606677661991-446cea8ee182?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFtYiUyMHNob3B8ZW58MHx8MHx8fDA%3D"
              },
                new Ingredient{
                //Id =  45,
                ItemName= "Tuna Steak",
                Protein= 29,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 144,
                Weight= 100,
                Fat= 1,
                ImageUrl="https://images.unsplash.com/photo-1501595091296-3aa970afb3ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VHVuYSUyMHN0ZWFrfGVufDB8fDB8fHww"
              },
                new Ingredient{
                //Id =  46,
                ItemName= "Shrimp",
                Protein= 24,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 1,
                Sugar = 0,
                Calories= 99,
                Weight= 100,
                Fat= 1,
                ImageUrl="https://images.unsplash.com/photo-1548587468-971ebe4c8c3b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hyaW1wfGVufDB8fDB8fHww"
              },
                new Ingredient{
                //Id =  47,
                ItemName= "Venison Steak",
                Protein= 30,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 158,
                Weight= 100,
                Fat= 4,
                ImageUrl="https://images.unsplash.com/photo-1597417175478-c161c1788242?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmVuaXNvbiUyMHN0ZWFrfGVufDB8fDB8fHww"
              },
                new Ingredient{
                //Id =  48,
                ItemName= "Duck Breast",
                Protein= 30,
                Type = FoodType.Meat_Poultry,
                Carbohydrates= 0,
                Sugar = 0,
                Calories= 337,
                Weight= 100,
                Fat= 30,
                ImageUrl="https://images.unsplash.com/photo-1580554530778-ca36943938b2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZHVjayUyMGJyZWFzdHxlbnwwfHwwfHx8MA%3D%3D"
              },
                new Ingredient{
              //Id =  49,
              ItemName = "Quinoa",
              Protein = 4,
              Type = FoodType.legumes,
              Carbohydrates = 21,
              Sugar = 2,
              Calories = 120,
              Weight = 100,
              Fat = 2,
              ImageUrl="https://plus.unsplash.com/premium_photo-1705003211073-353df1ce520a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fHF1aW5vYXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  50,
              ItemName = "Brown Rice",
              Protein = 2,
              Type = FoodType.legumes,
              Carbohydrates = 23,
              Sugar = 5,
              Calories = 111,
              Weight = 100,
              Fat = 1,
              ImageUrl="https://plus.unsplash.com/premium_photo-1671130295823-78f170465794?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGJyb3duJTIwcmljZXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  51,
              ItemName = "Barley",
              Protein = 3,
              Type = FoodType.legumes,
              Carbohydrates = 28,
              Sugar = 6,
              Calories = 123,
              Weight = 100,
              Fat = 1,
              ImageUrl="https://images.unsplash.com/photo-1534621735346-1de48541fa12?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8QmFybGV5fGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  52,
              ItemName = "Whole Wheat Pasta",
              Protein = 12,
              Type = FoodType.legumes,
              Carbohydrates = 25,
              Sugar = 6,
              Calories = 124,
              Weight = 100,
              Fat = 1,
              ImageUrl="https://plus.unsplash.com/premium_photo-1705404738237-20c799dcfe49?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8V2hvbGUlMjBXaGVhdCUyMFBhc3RhfGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  53,
              ItemName = "Buckwheat",
              Protein = 13,
              Type = FoodType.legumes,
              Carbohydrates = 20,
              Sugar = 6,
              Calories = 343,
              Weight = 100,
              Fat = 3,
              ImageUrl="https://images.unsplash.com/photo-1613758235306-69cc0a3f614d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVja3doZWF0fGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  54,
              ItemName = "Millet",
              Protein = 11,
              Type = FoodType.legumes,
              Carbohydrates = 22,
              Sugar = 6,
              Calories = 378,
              Weight = 100,
              Fat = 4,
              ImageUrl="https://plus.unsplash.com/premium_photo-1675237626370-caf08f2b9966?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8TWlsbGV0fGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  55,
              ItemName = "Spelt",
              Protein = 15,
              Type = FoodType.legumes,
              Carbohydrates = 28,
              Sugar = 6,
              Calories = 338,
              Weight = 100,
              Fat = 2,
              ImageUrl="https://images.unsplash.com/photo-1656918828529-345b77bb06e9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c3BlbHR8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  56,
              ItemName = "Oats",
              Protein = 17,
              Type = FoodType.legumes,
              Carbohydrates = 66,
              Sugar =1,
              Calories = 389,
              Weight = 100,
              Fat = 6,
              ImageUrl="https://images.unsplash.com/photo-1614373532018-92a75430a0da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8T2F0c3xlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  57,
              ItemName = "Amaranth",
              Protein = 14,
              Type = FoodType.legumes,
              Carbohydrates = 28,
              Sugar = 2,
              Calories = 371,
              Weight = 100,
              Fat = 7,
              ImageUrl="https://images.unsplash.com/photo-1586201375799-47cd24c3f595?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
            },
              new Ingredient{
              //Id =  58,
              ItemName = "Farro",
              Protein = 14,
              Type = FoodType.legumes,
              Carbohydrates = 28,
              Sugar = 4,
              Calories = 337,
              Weight = 100,
              Fat = 2,
              ImageUrl="https://www.jessicagavin.com/wp-content/uploads/2017/10/uncooked-farro-1200.jpg"
            },
              new Ingredient{
              //Id =  59,
              ItemName = "Coke",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 39,
              Sugar = 39,
              Calories = 140,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29rZXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  60,
              ItemName = "Coffee (Black)",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 2,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGNvZmZlZXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  61,
              ItemName = "Green Tea",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 0,
              Calories = 1,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1606441393961-bb2331b77d55?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGdyZWVuJTIwdGVhfGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  62,
              ItemName = "Orange Juice",
              Protein = 1,
              Type = FoodType.Drinks,
              Carbohydrates = 9,
              Sugar = 0,
              Calories = 45,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1577680716097-9a565ddc2007?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8b3JhbmdlJTIwanVpY2V8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  63,
              ItemName = "Milk",
              Protein = 3,
              Type = FoodType.Drinks,
              Carbohydrates = 5,
              Sugar = 12,
              Calories = 42,
              Weight = 100,
              Fat = 1,
              ImageUrl="https://images.unsplash.com/photo-1600788907416-456578634209?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWlsa3xlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  64,
              ItemName = "Sports Drink",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 6,
              Sugar = 15,
              Calories = 29,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1625865019554-220ea80ea813?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Z2F0b3JhZGV8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  65,
              ItemName = "Coconut Water",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 4,
              Sugar = 6,
              Calories = 19,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1518484157348-2cd88dc70d1f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y29jb251dCUyMHdhdGVyfGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  66,
              ItemName = "Almond Milk",
              Protein = 1,
              Type = FoodType.Drinks,
              Carbohydrates = 2,
              Sugar = 1,
              Calories = 17,
              Weight = 100,
              Fat = 1,
              ImageUrl="https://images.unsplash.com/photo-1601436423474-51738541c1b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QWxtb25kJTIwbWlsa3xlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  67,
              ItemName = "Lemonade",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 10,
              Sugar = 27,
              Calories = 44,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://plus.unsplash.com/premium_photo-1664391804722-cb3f2d439d7f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8TGVtb25hZGV8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  68,
              ItemName = "Iced Tea (Sweetened)",
              Protein = 0,
              Type = FoodType.Drinks,
              Carbohydrates = 11,
              Sugar = 25,
              Calories = 43,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aWNlZCUyMHRlYXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  70,
              ItemName = "Beer",
              Protein = 1,
              Type = FoodType.Alcohol,
              Carbohydrates = 13,
              Sugar = 15,
              Calories = 154,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8YmVlcnxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  71,
              ItemName = "Wine (Red)",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 4,
              Sugar = 2,
              Calories = 125,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2luZXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  72,
              ItemName = "Whiskey",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 97,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1546540749-3229ce1f48da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFdoaXNrZXl8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  73,
              ItemName = "Vodka",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1539606494565-02e568638d91?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Vm9ka2F8ZW58MHx8MHx8fDA%3D"
            },
              new Ingredient{
              //Id =  74,
              ItemName = "Rum",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cnVtfGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  75,
              ItemName = "Tequila",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1529671434436-8fbb37410056?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dGVxdWlsYXxlbnwwfHwwfHx8MA%3D%3D"
            },
              new Ingredient{
              //Id =  76,
              ItemName = "Gin",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8R2lufGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  77,
              ItemName = "Brandy",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://plus.unsplash.com/premium_photo-1661416364996-f865fcf5c290?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8QnJhbmR5fGVufDB8fDB8fHww"
            },
              new Ingredient{
              //Id =  78,
              ItemName = "Cognac",
              Protein = 0,
              Type = FoodType.Alcohol,
              Carbohydrates = 0,
              Sugar = 0,
              Calories = 231,
              Weight = 100,
              Fat = 0,
              ImageUrl="https://images.unsplash.com/photo-1602984156862-14b9ee0885c9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Q29nbmFjfGVufDB8fDB8fHww"
            },
              new Ingredient{
            //Id =  79,
            ItemName = "Almonds",
            Protein = 21,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 22,
            Sugar = 1,
            Calories = 579,
            Weight = 100,
            Fat = 49,
            ImageUrl="https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QWxtb25kc3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  80,
            ItemName = "Peanuts",
            Protein = 25,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 16,
            Sugar = 2,
            Calories = 567,
            Weight = 100,
            Fat = 49,
            ImageUrl="https://images.unsplash.com/photo-1549978113-29eb25c8177f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGVhbnV0c3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  81,
            ItemName = "Walnuts",
            Protein = 15,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 14,
            Sugar = 2,
            Calories = 654,
            Weight = 100,
            Fat = 65,
            ImageUrl="https://images.unsplash.com/photo-1524593000379-d4729b2c4f99?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2FsbnV0c3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  82,
            ItemName = "Cashews",
            Protein = 18,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 30,
            Sugar = 2,
            Calories = 553,
            Weight = 100,
            Fat = 44,
            ImageUrl="https://images.unsplash.com/photo-1573555657105-47a0bb37c3ea?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q2FzaGV3c3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  83,
            ItemName = "Pecans",
            Protein = 9,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 14,
            Sugar = 1,
            Calories = 691,
            Weight = 100,
            Fat = 72,
            ImageUrl="https://images.unsplash.com/photo-1582173649515-0f9582d58e60?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UGVjYW5zfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  84,
            ItemName = "Hazelnuts",
            Protein = 15,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 17,
            Sugar = 2,
            Calories = 628,
            Weight = 100,
            Fat = 61,
            ImageUrl="https://plus.unsplash.com/premium_photo-1668508855065-9402b77ffd67?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aGF6ZWxudXRzfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  85,
            ItemName = "Brazil Nuts",
            Protein = 14,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 12,
            Sugar = 2,
            Calories = 656,
            Weight = 100,
            Fat = 66,
            ImageUrl="https://images.unsplash.com/photo-1614807618553-35332e4de00d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnJhemlsJTIwbnV0c3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  86,
            ItemName = "Macadamia Nuts",
            Protein = 8,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 14,
            Sugar = 4,
            Calories = 718,
            Weight = 100,
            Fat = 76,
            ImageUrl="https://images.unsplash.com/photo-1579293675541-10fcb3725a19?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bWFjYWRhbWlhJTIwbnV0c3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  87,
            ItemName = "Pine Nuts",
            Protein = 13,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 14,
            Sugar = 3,
            Calories = 673,
            Weight = 100,
            Fat = 68,
            ImageUrl="https://images.unsplash.com/photo-1483915705094-ab1fe57ada9a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cGluZSUyMG51dHN8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  88,
            ItemName = "Pistachios",
            Protein = 21,
            Type = FoodType.nuts_Seeds,
            Carbohydrates = 28,
            Sugar = 2,
            Calories = 562,
            Weight = 100,
            Fat = 45,
            ImageUrl="https://images.unsplash.com/photo-1615485925933-379c8b6ad03c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGlzdGFjaGlvc3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  89,
            ItemName = "Olive Oil",
            Protein = 0,
            Type = FoodType.CookingOils,
            Carbohydrates = 0,
            Calories = 884,
            Weight = 100,
            Fat = 100,
            ImageUrl="https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b2xpdmUlMjBvaWx8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  90,
            ItemName = "Coconut Oil",
            Protein = 0,
            Type = FoodType.CookingOils,
            Carbohydrates = 0,
            Sugar = 0,
            Calories = 862,
            Weight = 100,
            Fat = 100,
            ImageUrl="https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBwbGV8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  91,
            ItemName = "Canola Oil",
            Protein = 0,
            Type = FoodType.CookingOils,
            Carbohydrates = 0,
            Sugar = 0,
            Calories = 884,
            Weight = 100,
            Fat = 100,
            ImageUrl="https://images.unsplash.com/photo-1552592074-ea7a91b851b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGNhbm9sYSUyMG9pbHxlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  92,
            ItemName = "Sesame Oil",
            Protein = 0,
            Type = FoodType.CookingOils,
            Carbohydrates = 0,
            Sugar = 0,
            Calories = 884,
            Weight = 100,
            Fat = 100,
            ImageUrl="https://images.unsplash.com/photo-1523071290596-8ad02685dcc0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2VzYW1lJTIwb2lsfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  93,
            ItemName = "Avocado Oil",
            Protein = 0,
            Type = FoodType.CookingOils,
            Carbohydrates = 0,
            Sugar = 0,
            Calories = 884,
            Weight = 100,
            Fat = 100,
            ImageUrl="https://images.unsplash.com/photo-1581264176930-2b8ab40dc90b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGF2b2NhZG8lMjBvaWx8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  94,
            ItemName = "Lentils",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 20,
            Sugar = 2,
            Calories = 116,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://images.unsplash.com/photo-1614373532201-c40b993f0013?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TGVudGlsc3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  95,
            ItemName = "Chickpeas",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 27,
            Sugar = 3,
            Calories = 164,
            Weight = 100,
            Fat = 3,
            ImageUrl="https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2twZWFzfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  96,
            ItemName = "Black Beans",
            Protein = 8,
            Type = FoodType.legumes,
            Carbohydrates = 63,
            Sugar = 1,
            Calories = 339,
            Weight = 100,
            Fat = 1,
            ImageUrl="https://plus.unsplash.com/premium_photo-1675237625091-e40de414b510?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBiZWFuc3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  97,
            ItemName = "Kidney Beans",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 22,
            Sugar = 1,
            Calories = 127,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://plus.unsplash.com/premium_photo-1671130295242-582789bd9861?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8a2lkbmV5JTIwYmVhbnN8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  98,
            ItemName = "Split Peas",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 63,
            Sugar = 1,
            Calories = 341,
            Weight = 100,
            Fat = 1,
            ImageUrl="https://plus.unsplash.com/premium_photo-1664007711018-d7cb92e664b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8U3BsaXQlMjBwZWFzfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  99,
            ItemName = "Green Peas",
            Protein = 5,
            Type = FoodType.legumes,
            Carbohydrates = 14,
            Sugar = 6,
            Calories = 81,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://images.unsplash.com/photo-1592394533824-9440e5d68530?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8R3JlZW4lMjBQZWFzfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  100,
            ItemName = "Soybeans",
            Protein = 36,
            Type = FoodType.legumes,
            Carbohydrates = 30,
            Sugar = 3,
            Calories = 446,
            Weight = 100,
            Fat = 20,
            ImageUrl="https://images.unsplash.com/photo-1639843606783-b2f9c50a7468?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U295YmVhbnN8ZW58MHx8MHx8fDA%3D"
          },
            new Ingredient{
            //Id =  101,
            ItemName = "Cannellini Beans",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 20,
            Sugar = 1,
            Calories = 127,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://plus.unsplash.com/premium_photo-1664527307810-63c15cb57346?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Q2FubmVsbGluaSUyMEJlYW5zfGVufDB8fDB8fHww"
          },
            new Ingredient{
            //Id =  102,
            ItemName = "Pinto Beans",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 22,
            Sugar = 2,
            Calories = 123,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://images.unsplash.com/photo-1612504258838-fbf14fe4437d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGludG8lMjBCZWFuc3xlbnwwfHwwfHx8MA%3D%3D"
          },
            new Ingredient{
            //Id =  103,
            ItemName = "Black-Eyed Peas",
            Protein = 9,
            Type = FoodType.legumes,
            Carbohydrates = 24,
            Sugar = 2,
            Calories = 134,
            Weight = 100,
            Fat = 0,
            ImageUrl="https://plus.unsplash.com/premium_photo-1670135170974-5352088c8ade?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBleWVkJTIwcGVhc3xlbnwwfHwwfHx8MA%3D%3D"
          }
              };

      await context.Ingredients.AddRangeAsync(item);//item);
      await context.SaveChangesAsync();

    }
  }
}